quarkus:
  http:
    port: 8082
mp:
  messaging:
    incoming:
      proposal:
        value:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
        connector: smallrye-kafka
        topic: proposal
